server:
  port: 88
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com/
          predicates:
            - Query=url,baidu.


    nacos:
      discovery:
        server-addr: localhost:8848
